name: test

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: |
                curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.SECRET}}>" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/inform-ttruong/gh-workflow-called/actions/workflows/test.yml/dispatches